#!/usr/bin/env ruby

# Translated from shell script at https://gist.github.com/strax/c0dcbfa2f9bb54f95787

SCHEMA_DEFINITION = /ActiveRecord::Schema\.define.version:\s([0-9_]+).\sdo/

CONFLICT_REGEX = /
^<+\s.*\n
#{SCHEMA_DEFINITION}\n
=+\n
#{SCHEMA_DEFINITION}\n
>+ .*
/x

ancestor_file, current_file, other_file, marker_size = ARGV # %O, %A, %B, %L
marker_size = Integer(marker_size)

system "git", "merge-file", "--marker-size=#{marker_size}", current_file, ancestor_file, other_file
current_content = File.read(current_file)

current_content.sub!(CONFLICT_REGEX) do
  "ActiveRecord::Schema.define(version: #{[Integer($1), Integer($2)].max}) do"
end

File.open(current_file, "w") {|f| f.write(current_content) }

# Other conflicts in the file, signal this to Git by exiting with error status
exit 1 if current_content.include?("<" * marker_size)
