{ config, lib, pkgs, ... }:

# Based on https://github.com/LnL7/nix-darwin/blob/007d700/modules/homebrew.nix

with lib;
with types;

let
  inherit (config) roles;
  inherit (config.lib.roles) mkOptionalRole;
  inherit (pkgs) mas;

  toCask = name: ''cask "${name}"'';
  toMas = name: id: ''mas "${name}", id: ${toString id}'';

  cfg = config.targets.darwin.homebrew;

  bundleFile = pkgs.writeText "Brewfile" ''
    # Automatically generated by home-manager

    # Casks
    ${concatMapStringsSep "\n" toCask cfg.casks}

    # App Store apps
    ${concatStringsSep "\n" (mapAttrsToList toMas cfg.masApps)}
  '';

in {
  options = {
    roles = {
      cyberduck = mkOptionalRole "Cyberduck";
      dropbox = mkOptionalRole "Dropbox";
      eqmac = mkOptionalRole "eqMac";
      gimp = mkOptionalRole "GIMP";
      harvest = mkOptionalRole "Harvest taskbar app";
      inkscape = mkOptionalRole "Inkscape";
      ngrok = mkOptionalRole "ngrok";
      postman = mkOptionalRole "Postman";
      slack = mkOptionalRole "Slack";
      sql-clients = mkOptionalRole "SQL clients (Sequel Pro, TablePlus)";
      virtualbox = mkOptionalRole "Virtual Box with extensions";
      whatsapp = mkOptionalRole "WhatsApp";
      zoom = mkOptionalRole "Zoom app";
    };

    targets.darwin.homebrew = {
      casks = mkOption {
        description = "Homebrew casks to install";
        type = listOf str;
      };

      masApps = mkOption {
        description = "Homebrew casks to install";
        type = attrsOf ints.positive;
      };
    };
  };

  config = {
    targets.darwin.homebrew = {
      casks = mkMerge [
        [
          "google-chrome"
          "firefox"

          "atom"
          "dash"
          "emacs"
          "iterm2"
          "kdiff3"
          "xquartz"

          # Quicklook plugins
          "qlcolorcode" # syntax highlighting
          "qlcommonmark" # markdown files
          "qlstephen" # files without extensions
          "quicklook-json"
          "quicklook-csv"

          "1password"
          "betterzip"
          "imageoptim"
          "keepingyouawake"
          "mollyguard"
          "superduper"
          "vlc"
        ]

        (mkIf roles.cyberduck ["cyberduck"])
        (mkIf roles.dropbox ["dropbox"])
        (mkIf roles.eqmac ["eqmac"])
        (mkIf roles.gimp ["gimp"])
        (mkIf roles.inkscape ["inkscape"])
        (mkIf roles.ngrok ["ngrok"])
        (mkIf roles.postman ["postman"])
        (mkIf roles.slack ["slack"])
        (mkIf roles.sql-clients ["sequel-pro" "tableplus"])
        (mkIf roles.virtualbox ["virtualbox" "virtualbox-extension-pack"])
        (mkIf roles.whatsapp ["whatsapp"])
        (mkIf roles.zoom ["zoom"])
      ];

      masApps = mkMerge [
        {
          Keynote = 409183694;
          Numbers = 409203825;
          Pages = 409201541;
          "HP Smart" = 1474276998;
        }

        (mkIf roles.harvest { Harvest = 506189836; })
      ];
    };

    programs.zsh.sessionVariables.HOMEBREW_BUNDLE_FILE = "${bundleFile}";

    home = {
      packages = [ mas ]; # make available for general use

      activation.homebrewBundle = lib.hm.dag.entryAfter ["installPackages"] ''
        $VERBOSE_ECHO "Installing Homebrew casks and MAS apps"

        # Ensure that `brew bundle` doesn't try to install `mas` itself
        export PATH="${mas}/bin:$PATH" HOMEBREW_NO_AUTO_UPDATE=1

        $DRY_RUN_CMD brew bundle install \
          $VERBOSE_ARG \
          --no-upgrade \
          --no-lock \
          --file="${bundleFile}"
      '';
    };
  };
}
