# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub, overrides ? (self: super: {}) }:

let
  packages = ( self:
{
  splitjoin-vim = buildVimPluginFrom2Nix {
    pname = "splitjoin-vim";
    version = "2020-02-08";
    src = fetchFromGitHub {
      owner = "AndrewRadev";
      repo = "splitjoin.vim";
      rev = "6bfdc927f858a514d7b9802dffe56be90d06ac10";
      sha256 = "05qifigwd3dl4jzzjgn13crzhzm7cw0bzxrsppkp7drza32r5hmd";
    };
  };

  vim-alias = buildVimPluginFrom2Nix {
    pname = "vim-alias";
    version = "2020-02-15";
    src = fetchFromGitHub {
      owner = "Konfekt";
      repo = "vim-alias";
      rev = "f0aa2bf9fbaa9e0d16c4b6d32841a126e41b9202";
      sha256 = "17cay94gvaqvxhq3vij2f8pcyfpgrf74lhwbwpwfciwqs9czg0hw";
    };
  };

  vim-bundler = buildVimPluginFrom2Nix {
    pname = "vim-bundler";
    version = "2019-11-13";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-bundler";
      rev = "0396ce134dd69b022c20b104c450c6121f0cb760";
      sha256 = "0crxib110l3d9vg63glbynxdifrawnsayhvjfqqiaiv31dz78q5h";
    };
  };

  vim-jsx = buildVimPluginFrom2Nix {
    pname = "vim-jsx";
    version = "2019-09-29";
    src = fetchFromGitHub {
      owner = "mxw";
      repo = "vim-jsx";
      rev = "8879e0d9c5ba0e04ecbede1c89f63b7a0efa24af";
      sha256 = "0czjily7kjw7bwmkxd8lqn5ncrazqjsfhsy3sf2wl9ni0r45cgcd";
    };
  };

  vim-mkdir = buildVimPluginFrom2Nix {
    pname = "vim-mkdir";
    version = "2019-04-29";
    src = fetchFromGitHub {
      owner = "pbrisbin";
      repo = "vim-mkdir";
      rev = "f0ba7a7dc190a0cedf1d827958c99f3718109cf0";
      sha256 = "0kp2n1wfmlcxcwpqp63gmzs8ihdhd5qcncc4dwycwr1sljklarnw";
    };
  };

  vim-prettier = buildVimPluginFrom2Nix {
    pname = "vim-prettier";
    version = "2020-02-18";
    src = fetchFromGitHub {
      owner = "prettier";
      repo = "vim-prettier";
      rev = "7041b9cb8bee84f432f1e168f826a90a0beea93a";
      sha256 = "13zfirw9n0bimcjh694sg98g4ixvv6jwja0zc6qnxkynwwygz63f";
    };
  };

  vim-rails = buildVimPluginFrom2Nix {
    pname = "vim-rails";
    version = "2020-01-17";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-rails";
      rev = "64befc6187678893082bebb8be79c1d17fdd07ba";
      sha256 = "1yjqxqx3g74afzdq8iqd6zw7ypn6dv1i14qi9a7jnnwnp956lc12";
    };
  };

  vim-rspec = buildVimPluginFrom2Nix {
    pname = "vim-rspec";
    version = "2017-01-30";
    src = fetchFromGitHub {
      owner = "thoughtbot";
      repo = "vim-rspec";
      rev = "52a72592b6128f4ef1557bc6e2e3eb014d8b2d38";
      sha256 = "09prk06rrbs8pgfm4iz88sp151p6pi9bl76p6macvv5nxv72d9j8";
    };
  };

  vim-ruby-refactoring = buildVimPluginFrom2Nix {
    pname = "vim-ruby-refactoring";
    version = "2011-12-28";
    src = fetchFromGitHub {
      owner = "ecomba";
      repo = "vim-ruby-refactoring";
      rev = "6447a4debc3263a0fa99feeab5548edf27ecf045";
      sha256 = "1fgwpfmzy3mfcx4cyfhmxk42np9g0bgp1nrc0w7vr9wlmzwn7mch";
    };
  };

  vim-rubyhash = buildVimPluginFrom2Nix {
    pname = "vim-rubyhash";
    version = "2011-12-27";
    src = fetchFromGitHub {
      owner = "rorymckinley";
      repo = "vim-rubyhash";
      rev = "d020a8eeac40a55617a72aa135b702b6da0c9b62";
      sha256 = "16shl7ww5qj4vqaai7crbsrrcvpdgrgww3n00lkzfyfp1chnhhd1";
    };
  };

  vim-textobj-rubyblock = buildVimPluginFrom2Nix {
    pname = "vim-textobj-rubyblock";
    version = "2016-09-13";
    src = fetchFromGitHub {
      owner = "nelstrom";
      repo = "vim-textobj-rubyblock";
      rev = "2b882e2cc2599078f75e6e88cd268192bf7b27bf";
      sha256 = "197m0a45ywdpq2iqng6mi5qjal2qggjjww1k95iz2s7wvh8ng9yr";
    };
  };

  vim-textobj-variable-segment = buildVimPluginFrom2Nix {
    pname = "vim-textobj-variable-segment";
    version = "2019-12-30";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "vim-textobj-variable-segment";
      rev = "78457d4322b44bf89730e708b62b69df48c39aa3";
      sha256 = "14dcrnk83hj4ixrkdgjrk9cf0193f82wqckdzd4w0b76adf3habj";
    };
  };

  vim-yaml-helper = buildVimPluginFrom2Nix {
    pname = "vim-yaml-helper";
    version = "2018-04-15";
    src = fetchFromGitHub {
      owner = "lmeijvogel";
      repo = "vim-yaml-helper";
      rev = "db031682d339f361e2f8ed213cdb2c505cd0e011";
      sha256 = "03c5xx7ikahkj5ngihjfznc3d3cfb7sw9lw2wlwvmmj9rinq8zil";
    };
  };

});
in lib.fix' (lib.extends overrides packages)
