{ config, lib, pkgs, machine, ... }:

# Based on https://github.com/LnL7/nix-darwin/blob/007d700/modules/homebrew.nix

with lib;
with types;

let
  runAsIntel = path: pkgs.writeShellScriptBin "${builtins.baseNameOf path}-wrapped" ''
    arch -x86_64 ${path} "$@"
  '';

  # We need to always run `mas` under Rosetta 2, since the changes
  # Nix makes to the executable invalidate its signature, and thus
  # Big Sur refuses to run it.
  mas = pkgs.buildEnv {
    inherit (pkgs.mas) meta passthru;

    name = "mas-intel";
    paths = [ pkgs.mas (runAsIntel "${pkgs.mas}/bin/mas") ];

    postBuild = ''
      rm $out/bin/mas
      mv $out/bin/mas-wrapped $out/bin/mas
    '';
  };

  toCask = { name, ...}: ''cask "${name}"'';
  toMas = name: id: ''mas "${name}", id: ${toString id}'';

  cfg = config.targets.darwin.homebrew;

  bundleFile = pkgs.writeText "Brewfile" ''
    # Automatically generated by home-manager

    # Casks
    ${concatMapStringsSep "\n" toCask cfg.casks}

    # App Store apps
    ${concatStringsSep "\n" (mapAttrsToList toMas cfg.masApps)}
  '';

  caskWithConfigType = submodule {
    options = {
      name = mkOption {
        description = "Name of cask";
        type = str;
      };

      privateFiles = mkOption {
        description = "Private files to symlink";
        type = listOf str;
        default = [];
      };

      defaults = mkOption {
        description = "macOS defaults to set";
        type = attrs;
        default = {};
      };
    };
  };

  extractedPrivateFiles = foldl' (acc: cask: acc ++ cask.privateFiles) [] cfg.casks;
  extractedDefaults = mkMerge (catAttrs "defaults" cfg.casks);

  archPrefix = optionalString machine.isARM "arch -arm64e";

in {
  options.targets.darwin.homebrew = {
    casks = mkOption {
      description = "Homebrew casks to install";
      type = listOf (coercedTo str (name: { inherit name; }) caskWithConfigType);
    };

    masApps = mkOption {
      description = "Homebrew casks to install";
      type = attrsOf ints.positive;
    };
  };

  config = {
    targets.darwin.defaults = extractedDefaults;

    programs.zsh.sessionVariables.HOMEBREW_BUNDLE_FILE = "${bundleFile}";

    home = {
      file = config.lib.symlinks.privateFiles extractedPrivateFiles;

      packages = [ mas ]; # make available for general use

      activation.homebrewBundle = lib.hm.dag.entryAfter ["installPackages"] ''
        $VERBOSE_ECHO "Installing Homebrew casks and MAS apps"

        # Ensure that `brew bundle` doesn't try to install `mas` itself
        export PATH="${mas}/bin:$PATH" HOMEBREW_NO_AUTO_UPDATE=1

        $DRY_RUN_CMD ${archPrefix} brew bundle install \
          $VERBOSE_ARG \
          --no-upgrade \
          --no-lock \
          --file="${bundleFile}"
      '';
    };
  };
}
