#!/bin/sh
set -e

if [ "$#" -eq 0 ]; then
  echo "Usage: $(basename "$0") [gem name...]" >&2
  exit 1
fi

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)

first_file=$(find "$script_dir" -name 'gem-*.rb' -print -quit)

for gem in $@; do
  cp "$first_file" "$script_dir/gem-$gem".rb

  echo "Added $(basename "$script_dir")/gem-$gem.rb"
done
