# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@heroku-cli/color-1.1.14" = {
      name = "_at_heroku-cli_slash_color";
      packageName = "@heroku-cli/color";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@heroku-cli/color/-/color-1.1.14.tgz";
        sha512 = "2JYy//YE2YINTe21hpdVMBNc7aYFkgDeY9JUz/BCjFZmYLn0UjGaCc4BpTcMGXNJwuqoUenw2WGOFGHsJqlIDw==";
      };
    };
    "@heroku-cli/command-8.3.0" = {
      name = "_at_heroku-cli_slash_command";
      packageName = "@heroku-cli/command";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@heroku-cli/command/-/command-8.3.0.tgz";
        sha512 = "gQoe6KnIr8q+JCYvO/6STRBsJXHw+UwwtNs5me5Zx/020u2S1I4oqi3KamcTeRTC7ZVORH3DfE30aA3HNgYXsA==";
      };
    };
    "@heroku-cli/notifications-1.2.2" = {
      name = "_at_heroku-cli_slash_notifications";
      packageName = "@heroku-cli/notifications";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@heroku-cli/notifications/-/notifications-1.2.2.tgz";
        sha512 = "bW2R/I2TpxECPMU8bqiY9rTDHZHjRmKNPWCmXZGCg1ko3NehYfF26i2KBZ8OW3pSwcUi/cWSGhytpLPonHfQ+g==";
      };
    };
    "@heroku-cli/plugin-run-3.8.10" = {
      name = "_at_heroku-cli_slash_plugin-run";
      packageName = "@heroku-cli/plugin-run";
      version = "3.8.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@heroku-cli/plugin-run/-/plugin-run-3.8.10.tgz";
        sha1 = "f7ba86965055196961997dfdbd9540a7e7c0dba4";
      };
    };
    "@oclif/errors-1.2.2" = {
      name = "_at_oclif_slash_errors";
      packageName = "@oclif/errors";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@oclif/errors/-/errors-1.2.2.tgz";
        sha512 = "Eq8BFuJUQcbAPVofDxwdE0bL14inIiwt5EaKRVY9ZDIG11jwdXZqiQEECJx0VfnLyUZdYfRd/znDI/MytdJoKg==";
      };
    };
    "@oclif/linewrap-1.0.0" = {
      name = "_at_oclif_slash_linewrap";
      packageName = "@oclif/linewrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@oclif/linewrap/-/linewrap-1.0.0.tgz";
        sha512 = "Ups2dShK52xXa8w6iBWLgcjPJWjais6KPJQq3gQ/88AY6BXoTX+MIGFPrWQO1KLMiQfoTpcLnUwloN4brrVUHw==";
      };
    };
    "@oclif/screen-1.0.4" = {
      name = "_at_oclif_slash_screen";
      packageName = "@oclif/screen";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@oclif/screen/-/screen-1.0.4.tgz";
        sha512 = "60CHpq+eqnTxLZQ4PGHYNwUX572hgpMHGPtTWMjdTMsAvlm69lZV/4ly6O3sAYkomo4NggGcomrDpBe34rxUqw==";
      };
    };
    "@sindresorhus/is-0.7.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-0.7.0.tgz";
        sha512 = "ONhaKPIufzzrlNbqtWFFd+jlnemX6lJAgq9ZeiZtS7I1PIf/la7CW4m83rTXRnVnsMbW2k56pGYu7AUFJD9Pow==";
      };
    };
    "ansi-escapes-1.4.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz";
        sha1 = "d3a8a83b319aa67793662b13e761c7911422306e";
      };
    };
    "ansi-escapes-3.2.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-3.2.0.tgz";
        sha512 = "cBhpre4ma+U0T1oM5fXg7Dy1Jw7zzwv7lt/GoCpr+hDQJoYnKVPLL4dCvSEFMmQurOQvSrwT7SL/DAlhBI97RQ==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ansi-regex-4.1.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-4.1.0.tgz";
        sha512 = "1apePfXM1UOSqw0o9IiFAovVz9M5S1Dg+4TrDwfMewQ6p/rmMueb7tWZjQ1rx4Loy1ArBggoqGpfqqdI4rondg==";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansicolors-0.3.2" = {
      name = "ansicolors";
      packageName = "ansicolors";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansicolors/-/ansicolors-0.3.2.tgz";
        sha1 = "665597de86a9ffe3aa9bfbe6cae5c6ea426b4979";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "cacheable-request-2.1.4" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-2.1.4.tgz";
        sha1 = "0d808801b6342ad33c91df9d0b44dc09b91e5c3d";
      };
    };
    "cardinal-2.1.1" = {
      name = "cardinal";
      packageName = "cardinal";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cardinal/-/cardinal-2.1.1.tgz";
        sha1 = "7cc1055d822d212954d07b085dea251cc7bc5505";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "clean-stack-1.3.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-1.3.0.tgz";
        sha1 = "9e821501ae979986c46b1d66d2d432db2fd4ae31";
      };
    };
    "clean-stack-2.2.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
        sha512 = "4diC9HaTE+KRAMWhDhrGOECgWZxoevMc5TlkObMqNSsVU62PYzXZ/SMTjzyGAFF1YusgxGcSWTEXBhp0CPwQ1A==";
      };
    };
    "cli-ux-4.9.3" = {
      name = "cli-ux";
      packageName = "cli-ux";
      version = "4.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-ux/-/cli-ux-4.9.3.tgz";
        sha512 = "/1owvF0SZ5Gn54cgrikJ0QskgTzeg30HGjkmjFoaHDJzAqFpuX1DBpFR8aLvsE1J5s9MgeYRENQK4BFwOag5VA==";
      };
    };
    "clone-response-1.0.2" = {
      name = "clone-response";
      packageName = "clone-response";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-response/-/clone-response-1.0.2.tgz";
        sha1 = "d1dc973920314df67fbeb94223b4ee350239e96b";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cross-spawn-6.0.5" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-6.0.5.tgz";
        sha512 = "eTVLrBSt7fjbDygz805pMnstIs2VTBNkRm0qxZd+M7A5XDdxVRWO5MxGBXZhjY4cqLYLdtrGqRf8mBPmzwSpWQ==";
      };
    };
    "debug-3.2.6" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.6.tgz";
        sha512 = "mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==";
      };
    };
    "debug-4.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.2.0.tgz";
        sha512 = "IX2ncY78vDTjZMFUdmsvIRFY2Cf4FnD0wRs+nQwJU8Lu99/tPFdb0VybiiMTPe3I6rQmwsqQqRBvxU+bZ/I8sg==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha1 = "80a4dd323748384bfa248083622aedec982adff3";
      };
    };
    "duplexer3-0.1.4" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.4.tgz";
        sha1 = "ee01dd1cac0ed3cbc7fdbea37dc0a8f1ce002ce2";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "eventsource-1.0.7" = {
      name = "eventsource";
      packageName = "eventsource";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventsource/-/eventsource-1.0.7.tgz";
        sha512 = "4Ln17+vVT0k8aWq+t/bF5arcS3EpT9gYtW66EPacdj/mAFevznsnyoHLPy2BA8gbIQeIHoPsvwmfBftfcG//BQ==";
      };
    };
    "execa-0.10.0" = {
      name = "execa";
      packageName = "execa";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.10.0.tgz";
        sha512 = "7XOMnz8Ynx1gGo/3hyV9loYNPWM94jG3+3T3Y8tsfSstFmETmENCMU/A/zj8Lyaj1lkgEepKepvd6240tBRvlw==";
      };
    };
    "extract-stack-1.0.0" = {
      name = "extract-stack";
      packageName = "extract-stack";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extract-stack/-/extract-stack-1.0.0.tgz";
        sha1 = "b97acaf9441eea2332529624b732fc5a1c8165fa";
      };
    };
    "from2-2.3.0" = {
      name = "from2";
      packageName = "from2";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/from2/-/from2-2.3.0.tgz";
        sha1 = "8bfb5502bde4a4d36cfdeea007fcca21d7e382af";
      };
    };
    "fs-extra-6.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-6.0.1.tgz";
        sha512 = "GnyIkKhhzXZUWFCaJzvyDLEEgDkPfb4/TPvJCJVuS8MWZgoSsErf++QpiAlDnKFcqhRlm+tIOcencCjyJE6ZCA==";
      };
    };
    "fs-extra-7.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-7.0.1.tgz";
        sha512 = "YJDaCJZEnBmcbw13fvdAM9AwNOJwOzrE4pqMqBq5nFiEqXUqHwlK4B+3pUw6JNvfSPtX05xFHtYy/1ni01eGCw==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "get-stream-3.0.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-3.0.0.tgz";
        sha1 = "8e943d1358dc37555054ecbe2edb05aa174ede14";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "got-8.3.2" = {
      name = "got";
      packageName = "got";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-8.3.2.tgz";
        sha512 = "qjUJ5U/hawxosMryILofZCkm3C84PLJS/0grRIpjAwu+Lkxxj5cxeCU25BG0/3mDSpXKTyZr8oh8wIgLaH0QCw==";
      };
    };
    "graceful-fs-4.2.4" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.4.tgz";
        sha512 = "WjKPNJF79dtJAVniUlGGWHYGz2jWxT6VhN/4m1NdkbZ2nOsEF+cI1Edgql5zCRhs/VsQYRvrXctxktVXZUkixw==";
      };
    };
    "growly-1.3.0" = {
      name = "growly";
      packageName = "growly";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/growly/-/growly-1.3.0.tgz";
        sha1 = "f10748cbe76af964b7c96c93c6bcc28af120c081";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-2.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-2.0.0.tgz";
        sha1 = "e8207af1cc7b30d446cc70b734b5e8be18f88d51";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-symbol-support-x-1.4.2" = {
      name = "has-symbol-support-x";
      packageName = "has-symbol-support-x";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbol-support-x/-/has-symbol-support-x-1.4.2.tgz";
        sha512 = "3ToOva++HaW+eCpgqZrCfN51IPB+7bJNVT6CUATzueB5Heb8o6Nam0V3HG5dlDvZU1Gn5QLcbahiKw/XVk5JJw==";
      };
    };
    "has-to-string-tag-x-1.4.1" = {
      name = "has-to-string-tag-x";
      packageName = "has-to-string-tag-x";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-to-string-tag-x/-/has-to-string-tag-x-1.4.1.tgz";
        sha512 = "vdbKfmw+3LoOYVr+mtxHaX5a96+0f3DljYd8JOqvOLsf5mw2Otda2qCDT9qRqLAhrjyQ0h7ual5nOiASpsGNFw==";
      };
    };
    "heroku-cli-util-8.0.12" = {
      name = "heroku-cli-util";
      packageName = "heroku-cli-util";
      version = "8.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/heroku-cli-util/-/heroku-cli-util-8.0.12.tgz";
        sha512 = "63wB17oSktlA/HzpIV/PGe8Isq5AZArT51KAW1gg54zyYRIiHOwXik93HZuuRVUaVrWvVUhItFeLgqMwAwlTsw==";
      };
    };
    "heroku-client-3.1.0" = {
      name = "heroku-client";
      packageName = "heroku-client";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/heroku-client/-/heroku-client-3.1.0.tgz";
        sha512 = "UfGKwUm5duzzSVI8uUXlNAE1mus6uPxmZPji4vuG1ArV5DYL1rXsZShp0OoxraWdEwYoxCUrM6KGztC68x5EZQ==";
      };
    };
    "http-cache-semantics-3.8.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "3.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-3.8.1.tgz";
        sha512 = "5ai2iksyV8ZXmnZhHH4rWPoxxistEexSi5936zIQ1bnNTW5VnA85B6P/VpXiRM017IgRvb2kKo1a//y+0wSp3w==";
      };
    };
    "http-call-5.3.0" = {
      name = "http-call";
      packageName = "http-call";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-call/-/http-call-5.3.0.tgz";
        sha512 = "ahwimsC23ICE4kPl9xTBjKB4inbRaeLyZeRunC/1Jy/Z6X8tv22MEAjK+KBOMSVLaqXPTTmd8638waVIKLGx2w==";
      };
    };
    "hyperlinker-1.0.0" = {
      name = "hyperlinker";
      packageName = "hyperlinker";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyperlinker/-/hyperlinker-1.0.0.tgz";
        sha512 = "Ty8UblRWFEcfSuIaajM34LdPXIhbs1ajEX/BBPv24J+enSVaEVY63xQ6lTO9VRYS5LAoghIG0IDJ+p+IPzKUQQ==";
      };
    };
    "indent-string-3.2.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-3.2.0.tgz";
        sha1 = "4a5fd6d27cc332f37e5419a504dbb837105c9289";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "into-stream-3.1.0" = {
      name = "into-stream";
      packageName = "into-stream";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/into-stream/-/into-stream-3.1.0.tgz";
        sha1 = "96fb0a936c12babd6ff1752a17d05616abd094c6";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "is-object-1.0.1" = {
      name = "is-object";
      packageName = "is-object";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-object/-/is-object-1.0.1.tgz";
        sha1 = "8952688c5ec2ffd6b03ecc85e769e02903083470";
      };
    };
    "is-plain-obj-1.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
        sha1 = "71a50c8429dfca773c92a390a4a03b39fcd51d3e";
      };
    };
    "is-retry-allowed-1.2.0" = {
      name = "is-retry-allowed";
      packageName = "is-retry-allowed";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-retry-allowed/-/is-retry-allowed-1.2.0.tgz";
        sha512 = "RUbUeKwvm3XG2VYamhJL1xFktgjvPzL0Hq8C+6yrWIswDy3BIXGqCxhxkc30N9jqK311gVU137K8Ei55/zVJRg==";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "is-stream-2.0.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.0.tgz";
        sha512 = "XCoy+WlUr7d1+Z8GgSuXmpuUFC9fOhRXglJMx+dwLKTkL44Cjd4W1Z5P+BQZpr+cR93aGP4S/s7Ftw6Nd/kiEw==";
      };
    };
    "is-wsl-1.1.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-1.1.0.tgz";
        sha1 = "1f16e4aa22b04d1336b66188a66af3c600c3a66d";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isurl-1.0.0" = {
      name = "isurl";
      packageName = "isurl";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isurl/-/isurl-1.0.0.tgz";
        sha512 = "1P/yWsxPlDtn7QeRD+ULKQPaIaN6yF368GZ2vDfv0AL0NwpStafjWCDDdn0k8wgFMWpVAqG7oJhxHnlud42i9w==";
      };
    };
    "json-buffer-3.0.0" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.0.tgz";
        sha1 = "5b1f397afc75d677bde8bcfc0e47e1f9a3d9a898";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "keyv-3.0.0" = {
      name = "keyv";
      packageName = "keyv";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-3.0.0.tgz";
        sha512 = "eguHnq22OE3uVoSYG0LVWNP+4ppamWr9+zWBe1bsNcovIMy6huUJFPgy4mGwCd/rnl3vOLGW1MTlu4c57CT1xA==";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "lowercase-keys-1.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz";
        sha1 = "4e3366b39e7f5457e35f1324bdf6f88d0bfc7306";
      };
    };
    "lowercase-keys-1.0.1" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.1.tgz";
        sha512 = "G2Lj61tXDnVFFOi8VZds+SoQjtQC3dgokKdDG2mTm1tx4m50NUHBOZSBwQQHyy0V12A0JTG4icfZQH+xPyh8VA==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "netrc-0.1.4" = {
      name = "netrc";
      packageName = "netrc";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/netrc/-/netrc-0.1.4.tgz";
        sha1 = "6be94fcaca8d77ade0a9670dc460914c94472444";
      };
    };
    "netrc-parser-3.1.6" = {
      name = "netrc-parser";
      packageName = "netrc-parser";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/netrc-parser/-/netrc-parser-3.1.6.tgz";
        sha512 = "lY+fmkqSwntAAjfP63jB4z5p5WbuZwyMCD3pInT7dpHU/Gc6Vv90SAC6A0aNiqaRGHiuZFBtiwu+pu8W/Eyotw==";
      };
    };
    "nice-try-1.0.5" = {
      name = "nice-try";
      packageName = "nice-try";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nice-try/-/nice-try-1.0.5.tgz";
        sha512 = "1nh45deeb5olNY7eX82BkPO7SSxR5SSYJiPTrTdFUVYwAl8CKMA5N9PjTYkHiRjisVcxcQ1HXdLhx2qxxJzLNQ==";
      };
    };
    "node-notifier-5.4.3" = {
      name = "node-notifier";
      packageName = "node-notifier";
      version = "5.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-notifier/-/node-notifier-5.4.3.tgz";
        sha512 = "M4UBGcs4jeOK9CjTsYwkvH6/MzuUmGCyTW+kCY7uO+1ZVr0+FHGdPdIf5CCLqAaxnRrWidyoQlNkMIIVwbKB8Q==";
      };
    };
    "normalize-url-2.0.1" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-2.0.1.tgz";
        sha512 = "D6MUW4K/VzoJ4rJ01JFKxDrtY1v9wrgzCX5f2qj/lzH1m/lW6MhUZFKerVsnyjOhOsYzI9Kqqak+10l4LvLpMw==";
      };
    };
    "npm-run-path-2.0.2" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-2.0.2.tgz";
        sha1 = "35a9232dfa35d7067b4cb2ddf2357b1871536c5f";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "open-6.4.0" = {
      name = "open";
      packageName = "open";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-6.4.0.tgz";
        sha512 = "IFenVPgF70fSm1keSd2iDBIDIBZkroLeuffXq+wKTzTJlBpesFWojV9lb8mzOfaAzM1sr7HQHuO0vtV0zYekGg==";
      };
    };
    "opn-3.0.3" = {
      name = "opn";
      packageName = "opn";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/opn/-/opn-3.0.3.tgz";
        sha1 = "b6d99e7399f78d65c3baaffef1fb288e9b85243a";
      };
    };
    "original-1.0.2" = {
      name = "original";
      packageName = "original";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/original/-/original-1.0.2.tgz";
        sha512 = "hyBVl6iqqUOJ8FqRe+l/gS8H+kKYjrEndd5Pm1MfBtsEKA038HkkdbAl/72EAXGyonD/PFsvmVG+EvcIpliMBg==";
      };
    };
    "p-cancelable-0.4.1" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-0.4.1.tgz";
        sha512 = "HNa1A8LvB1kie7cERyy21VNeHb2CWJJYqyyC2o3klWFfMGlFmWv2Z7sFgZH8ZiaYL95ydToKTFVXgMV/Os0bBQ==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "p-is-promise-1.1.0" = {
      name = "p-is-promise";
      packageName = "p-is-promise";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-is-promise/-/p-is-promise-1.1.0.tgz";
        sha1 = "9c9456989e9f6588017b0434d56097675c3da05e";
      };
    };
    "p-timeout-2.0.1" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-2.0.1.tgz";
        sha512 = "88em58dDVB/KzPEx1X0N3LwFfYZPyDc4B6eF38M1rk9VTZMbxXXgjugz8mmwpS9Ox4BDZ+t6t3QP5+/gazweIA==";
      };
    };
    "parse-json-4.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-4.0.0.tgz";
        sha1 = "be35f5425be1f7f6c747184f98a788cb99477ee0";
      };
    };
    "password-prompt-1.1.2" = {
      name = "password-prompt";
      packageName = "password-prompt";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/password-prompt/-/password-prompt-1.1.2.tgz";
        sha512 = "bpuBhROdrhuN3E7G/koAju0WjVw9/uQOG5Co5mokNj0MiOSBVZS1JTwM4zl55hu0WFmIEFvO9cU9sJQiBIYeIA==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-key-2.0.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha1 = "411cadb574c5a140d3a4b1910d40d80cc9f40b40";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha1 = "e5a4acd2c101fdf3d9a4d07f0dbc4db49dd28176";
      };
    };
    "prepend-http-2.0.0" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-2.0.0.tgz";
        sha1 = "e92434bfa5ea8c19f41cdfd401d741a3c819d897";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "query-string-5.1.1" = {
      name = "query-string";
      packageName = "query-string";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-5.1.1.tgz";
        sha512 = "gjWOsm2SoGlgLEdAGt7a6slVOk9mGiXmPFMqrEhLQ68rhQuBnpfs3+EmlvqKyxnCo9/PPlF+9MtY02S1aFg+Jw==";
      };
    };
    "querystringify-2.1.1" = {
      name = "querystringify";
      packageName = "querystringify";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystringify/-/querystringify-2.1.1.tgz";
        sha512 = "w7fLxIRCRT7U8Qu53jQnJyPkYZIaR4n5151KMfcJlO/A9397Wxb1amJvROTK6TOnp7PfoAmg/qXiNHI+08jRfA==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "redeyed-2.1.1" = {
      name = "redeyed";
      packageName = "redeyed";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redeyed/-/redeyed-2.1.1.tgz";
        sha1 = "8984b5815d99cb220469c99eeeffe38913e6cc0b";
      };
    };
    "requires-port-1.0.0" = {
      name = "requires-port";
      packageName = "requires-port";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz";
        sha1 = "925d2601d39ac485e091cf0da5c6e694dc3dcaff";
      };
    };
    "responselike-1.0.2" = {
      name = "responselike";
      packageName = "responselike";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-1.0.2.tgz";
        sha1 = "918720ef3b631c5642be068f15ade5a46f4ba1e7";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "shellwords-0.1.1" = {
      name = "shellwords";
      packageName = "shellwords";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shellwords/-/shellwords-0.1.1.tgz";
        sha512 = "vFwSUfQvqybiICwZY5+DAWIPLKsWO31Q91JSKl3UYv+K5c2QRPzn0qzec6QPu1Qc9eHYItiP3NdJqNVqetYAww==";
      };
    };
    "signal-exit-3.0.3" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.3.tgz";
        sha512 = "VUJ49FC8U1OxwZLxIbTTrDvLnf/6TDgxZcK8wxR8zs13xpx7xbG60ndBlhNrFi2EMuFRoeDoJO7wthSLq42EjA==";
      };
    };
    "smooth-progress-1.1.0" = {
      name = "smooth-progress";
      packageName = "smooth-progress";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smooth-progress/-/smooth-progress-1.1.0.tgz";
        sha1 = "a51d6dbc2b1c4635ac94bf4be89364d5ce91ce32";
      };
    };
    "sort-keys-2.0.0" = {
      name = "sort-keys";
      packageName = "sort-keys";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sort-keys/-/sort-keys-2.0.0.tgz";
        sha1 = "658535584861ec97d730d6cf41822e1f56684128";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "strict-uri-encode-1.1.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-1.1.0.tgz";
        sha1 = "279b225df1d582b1f54e65addd4352e18faa0713";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "strip-ansi-5.2.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-5.2.0.tgz";
        sha512 = "DuRs1gKbBqsMKIZlrffwlug8MHkcnpjs5VPmL1PAh+mA30U0DTotfDZ0d2UUsXpPmPmMMJ6W773MaA3J+lbiWA==";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-hyperlinks-1.0.1" = {
      name = "supports-hyperlinks";
      packageName = "supports-hyperlinks";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-hyperlinks/-/supports-hyperlinks-1.0.1.tgz";
        sha512 = "HHi5kVSefKaJkGYXbDuKbUGRVxqnWGn3J2e39CYcNJEfWciGq2zYtOhXLTlvrOZW1QU7VX67w7fMmWafHX9Pfw==";
      };
    };
    "timed-out-4.0.1" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-4.0.1.tgz";
        sha1 = "f32eacac5a175bea25d7fab565ab3ed8741ef56f";
      };
    };
    "treeify-1.1.0" = {
      name = "treeify";
      packageName = "treeify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/treeify/-/treeify-1.1.0.tgz";
        sha512 = "1m4RA7xVAJrSGrrXGs0L3YTwyvBs2S8PbRHaLZAkFw7JR8oIFwYtysxlBZhYIa7xSyiYJKZ3iGrrk55cGA3i9A==";
      };
    };
    "tslib-1.13.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.13.0.tgz";
        sha512 = "i/6DQjL8Xf3be4K/E6Wgpekn5Qasl1usyw++dAA35Ue5orEn65VIxOA+YvNNl9HV3qv70T7CNwjODHZrLwvd1Q==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "universalify-0.1.2" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
        sha512 = "rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
      };
    };
    "url-parse-1.4.7" = {
      name = "url-parse";
      packageName = "url-parse";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse/-/url-parse-1.4.7.tgz";
        sha512 = "d3uaVyzDB9tQoSXFvuSUNFibTd9zxd2bkVrDRvF5TmvWWQwqE4lgYJ5m+x1DbecWkw+LK4RNl2CU1hHuOKPVlg==";
      };
    };
    "url-parse-lax-3.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-3.0.0.tgz";
        sha1 = "16b5cafc07dbe3676c1b1999177823d6503acb0c";
      };
    };
    "url-to-options-1.0.1" = {
      name = "url-to-options";
      packageName = "url-to-options";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-to-options/-/url-to-options-1.0.1.tgz";
        sha1 = "1505a03a289a48cbd7a434efbaeec5055f5633a9";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "wrap-ansi-4.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-4.0.0.tgz";
        sha512 = "uMTsj9rDb0/7kk1PbcbCcwvHUxp60fGDB/NNXpVa0Q+ic/e7y5+BwTxKfQ33VYgDppSwi/FBzpetYzo8s6tfbg==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yamljs-0.3.0" = {
      name = "yamljs";
      packageName = "yamljs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yamljs/-/yamljs-0.3.0.tgz";
        sha512 = "C/FsVVhht4iPQYXOInoxUM/1ELSf9EsgKH34FofQOp6hwCPrW4vG4w5++TED3xRUo8gD7l0P1J1dLlDYzODsTQ==";
      };
    };
  };
in
{
  heroku-accounts = nodeEnv.buildNodePackage {
    name = "heroku-accounts";
    packageName = "heroku-accounts";
    version = "1.1.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/heroku-accounts/-/heroku-accounts-1.1.7.tgz";
      sha512 = "gxXiUh8RTURgc6s6Gocd1McQrC2m+MQdVu85M6wDa3U8mh/7hlzhxjrhgTgRDuJnHsU6w30YFxryTIfIUtjK3A==";
    };
    dependencies = [
      (sources."@heroku-cli/color-1.1.14" // {
        dependencies = [
          sources."strip-ansi-5.2.0"
        ];
      })
      sources."@sindresorhus/is-0.7.0"
      sources."ansi-escapes-3.2.0"
      sources."ansi-regex-4.1.0"
      sources."ansi-styles-3.2.1"
      sources."ansicolors-0.3.2"
      sources."argparse-1.0.10"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      (sources."cacheable-request-2.1.4" // {
        dependencies = [
          sources."lowercase-keys-1.0.0"
        ];
      })
      sources."cardinal-2.1.1"
      sources."chalk-2.4.2"
      sources."clone-response-1.0.2"
      sources."co-4.6.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."core-util-is-1.0.2"
      sources."cross-spawn-6.0.5"
      sources."debug-3.2.6"
      sources."decode-uri-component-0.2.0"
      sources."decompress-response-3.3.0"
      sources."duplexer3-0.1.4"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."execa-0.10.0"
      sources."from2-2.3.0"
      sources."fs.realpath-1.0.0"
      sources."get-stream-3.0.0"
      sources."glob-7.1.6"
      sources."got-8.3.2"
      sources."has-flag-3.0.0"
      sources."has-symbol-support-x-1.4.2"
      sources."has-to-string-tag-x-1.4.1"
      sources."heroku-cli-util-8.0.12"
      sources."heroku-client-3.1.0"
      sources."http-cache-semantics-3.8.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."into-stream-3.1.0"
      sources."is-object-1.0.1"
      sources."is-plain-obj-1.1.0"
      sources."is-retry-allowed-1.2.0"
      sources."is-stream-1.1.0"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."isurl-1.0.0"
      sources."json-buffer-3.0.0"
      sources."keyv-3.0.0"
      sources."lodash-4.17.15"
      sources."lowercase-keys-1.0.1"
      sources."mimic-response-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."ms-2.1.2"
      sources."netrc-0.1.4"
      sources."netrc-parser-3.1.6"
      sources."nice-try-1.0.5"
      sources."normalize-url-2.0.1"
      sources."npm-run-path-2.0.2"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."opn-3.0.3"
      sources."p-cancelable-0.4.1"
      sources."p-finally-1.0.0"
      sources."p-is-promise-1.1.0"
      sources."p-timeout-2.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-key-2.0.1"
      sources."pify-3.0.0"
      sources."prepend-http-2.0.0"
      sources."process-nextick-args-2.0.1"
      sources."query-string-5.1.1"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."redeyed-2.1.1"
      sources."responselike-1.0.2"
      sources."safe-buffer-5.2.1"
      sources."semver-5.7.1"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."signal-exit-3.0.3"
      sources."sort-keys-2.0.0"
      sources."sprintf-js-1.0.3"
      sources."strict-uri-encode-1.1.0"
      (sources."string_decoder-1.1.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      (sources."strip-ansi-4.0.0" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
        ];
      })
      sources."strip-eof-1.0.0"
      sources."supports-color-5.5.0"
      sources."timed-out-4.0.1"
      sources."tslib-1.13.0"
      sources."tunnel-agent-0.6.0"
      sources."url-parse-lax-3.0.0"
      sources."url-to-options-1.0.1"
      sources."util-deprecate-1.0.2"
      sources."which-1.3.1"
      sources."wrappy-1.0.2"
      sources."yamljs-0.3.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "manage multiple heroku accounts";
      homepage = https://github.com/heroku/heroku-accounts;
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  heroku-repo = nodeEnv.buildNodePackage {
    name = "heroku-repo";
    packageName = "heroku-repo";
    version = "1.0.14";
    src = fetchurl {
      url = "https://registry.npmjs.org/heroku-repo/-/heroku-repo-1.0.14.tgz";
      sha512 = "HC2ZwSC0HaDuCfCs0eMMfKCQBZgn0GjYfiL+4tdgXK7F58yf34+eyISYUTrNJFliOLHDab5sReUMRNplyqV73w==";
    };
    dependencies = [
      sources."@heroku-cli/color-1.1.14"
      (sources."@heroku-cli/command-8.3.0" // {
        dependencies = [
          sources."fs-extra-7.0.1"
        ];
      })
      sources."@heroku-cli/notifications-1.2.2"
      sources."@heroku-cli/plugin-run-3.8.10"
      (sources."@oclif/errors-1.2.2" // {
        dependencies = [
          sources."fs-extra-7.0.1"
        ];
      })
      sources."@oclif/linewrap-1.0.0"
      sources."@oclif/screen-1.0.4"
      sources."@sindresorhus/is-0.7.0"
      sources."ansi-escapes-3.2.0"
      sources."ansi-regex-4.1.0"
      sources."ansi-styles-3.2.1"
      sources."ansicolors-0.3.2"
      sources."bytes-3.0.0"
      (sources."cacheable-request-2.1.4" // {
        dependencies = [
          sources."lowercase-keys-1.0.0"
        ];
      })
      sources."cardinal-2.1.1"
      sources."chalk-2.4.2"
      sources."clean-stack-1.3.0"
      (sources."cli-ux-4.9.3" // {
        dependencies = [
          sources."clean-stack-2.2.0"
          sources."fs-extra-7.0.1"
        ];
      })
      sources."clone-response-1.0.2"
      sources."co-4.6.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."content-type-1.0.4"
      sources."core-util-is-1.0.2"
      sources."cross-spawn-6.0.5"
      sources."debug-4.2.0"
      sources."decode-uri-component-0.2.0"
      sources."decompress-response-3.3.0"
      sources."duplexer3-0.1.4"
      sources."error-ex-1.3.2"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."eventsource-1.0.7"
      (sources."execa-0.10.0" // {
        dependencies = [
          sources."is-stream-1.1.0"
        ];
      })
      sources."extract-stack-1.0.0"
      sources."from2-2.3.0"
      sources."fs-extra-6.0.1"
      sources."get-stream-3.0.0"
      sources."got-8.3.2"
      sources."graceful-fs-4.2.4"
      sources."growly-1.3.0"
      (sources."has-ansi-2.0.0" // {
        dependencies = [
          sources."ansi-regex-2.1.1"
        ];
      })
      sources."has-flag-3.0.0"
      sources."has-symbol-support-x-1.4.2"
      sources."has-to-string-tag-x-1.4.1"
      (sources."heroku-cli-util-8.0.12" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
          sources."strip-ansi-4.0.0"
        ];
      })
      sources."heroku-client-3.1.0"
      sources."http-cache-semantics-3.8.1"
      sources."http-call-5.3.0"
      sources."hyperlinker-1.0.0"
      sources."indent-string-3.2.0"
      sources."inherits-2.0.4"
      sources."into-stream-3.1.0"
      sources."is-arrayish-0.2.1"
      sources."is-fullwidth-code-point-2.0.0"
      sources."is-object-1.0.1"
      sources."is-plain-obj-1.1.0"
      sources."is-retry-allowed-1.2.0"
      sources."is-stream-2.0.0"
      sources."is-wsl-1.1.0"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."isurl-1.0.0"
      sources."json-buffer-3.0.0"
      sources."json-parse-better-errors-1.0.2"
      sources."jsonfile-4.0.0"
      sources."keyv-3.0.0"
      sources."lodash-4.17.15"
      sources."lowercase-keys-1.0.1"
      sources."mimic-response-1.0.1"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."ms-2.1.2"
      (sources."netrc-parser-3.1.6" // {
        dependencies = [
          sources."debug-3.2.6"
        ];
      })
      sources."nice-try-1.0.5"
      sources."node-notifier-5.4.3"
      sources."normalize-url-2.0.1"
      sources."npm-run-path-2.0.2"
      sources."object-assign-4.1.1"
      sources."open-6.4.0"
      sources."opn-3.0.3"
      sources."original-1.0.2"
      sources."p-cancelable-0.4.1"
      sources."p-finally-1.0.0"
      sources."p-is-promise-1.1.0"
      sources."p-timeout-2.0.1"
      sources."parse-json-4.0.0"
      sources."password-prompt-1.1.2"
      sources."path-key-2.0.1"
      sources."pify-3.0.0"
      sources."prepend-http-2.0.0"
      sources."process-nextick-args-2.0.1"
      sources."query-string-5.1.1"
      sources."querystringify-2.1.1"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."redeyed-2.1.1"
      sources."requires-port-1.0.0"
      sources."responselike-1.0.2"
      sources."safe-buffer-5.2.1"
      sources."semver-5.7.1"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."shellwords-0.1.1"
      sources."signal-exit-3.0.3"
      (sources."smooth-progress-1.1.0" // {
        dependencies = [
          sources."ansi-escapes-1.4.0"
          sources."ansi-regex-2.1.1"
          sources."ansi-styles-2.2.1"
          sources."chalk-1.1.3"
          sources."strip-ansi-3.0.1"
          sources."supports-color-2.0.0"
        ];
      })
      sources."sort-keys-2.0.0"
      sources."strict-uri-encode-1.1.0"
      (sources."string-width-2.1.1" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
          sources."strip-ansi-4.0.0"
        ];
      })
      (sources."string_decoder-1.1.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."strip-ansi-5.2.0"
      sources."strip-eof-1.0.0"
      sources."supports-color-5.5.0"
      (sources."supports-hyperlinks-1.0.1" // {
        dependencies = [
          sources."has-flag-2.0.0"
        ];
      })
      sources."timed-out-4.0.1"
      sources."treeify-1.1.0"
      sources."tslib-1.13.0"
      sources."tunnel-agent-0.6.0"
      sources."universalify-0.1.2"
      sources."url-parse-1.4.7"
      sources."url-parse-lax-3.0.0"
      sources."url-to-options-1.0.1"
      sources."util-deprecate-1.0.2"
      sources."which-1.3.1"
      (sources."wrap-ansi-4.0.0" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
          sources."strip-ansi-4.0.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Heroku CLI plugin to manipulate the repo";
      homepage = https://github.com/heroku/heroku-repo;
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}