#!/bin/sh

set -e

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
host="$1"

if [ -z "$host" ]; then
  echo "Provide a host" > /dev/stderr
  exit 1
fi

run_with_log() {
  local dir="$script_dir/../setup"

  "$dir/run_with_log" "$dir/$1"
}

run_with_log basics.sh

ln -siv "$script_dir/../hosts/$host/.system_tags" "$HOME/.system_tags"

run_with_log bootstrap.sh

run_with_log .macos
