#!/bin/bash
set -euo pipefail

dotfiles="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)"

fail() {
  echo >&2 "$1"
  exit 1
}

currentGeneration() {
  /usr/bin/readlink "${NIX_STATE_DIR:-"/nix/var/nix"}/profiles/per-user/$USER/profile" \
    | awk -F- '{ print $2 }'
}

hostId="$(scutil --get LocalHostName | sed -e 's/^rjp-//')"

[ -n "$hostId" ] || fail "Unable to determine hostname"

hasNixBuild=""
hasNixProfile=""

if command -v nix-build > /dev/null; then
  hasNixBuild="1"
fi

if [ -n "${NIX_PROFILES:-}" ]; then
  hasNixProfile="1"
fi

if [ -z "$hasNixBuild" ] || [ -z "$hasNixProfile" ]; then
  nixVersion="$(awk -F\" '/NIX_VERSION=/{print $2}' "$dotfiles/script/bootstrap")"
  [ -n "$nixVersion" ] || fail "Unable to get Nix version"

  nixPath="$(find "${NIX_STORE_DIR:="/nix/store"}" -depth 1 -name "*-nix-$nixVersion" | head -n 1)"
  [ -n "$nixPath" ] || fail "Unable to find Nix derivation in Nix store"

  # shellcheck disable=SC1072,SC1091
  [ -n "$hasNixProfile" ] || source "$nixPath/etc/profile.d/nix.sh"
  [ -n "$hasNixBuild" ] || export PATH="$nixPath/bin:$PATH"
fi

# Ensure that `nix.conf` is still found even when not
# symlinked into `~/.config`
export NIX_CONF_DIR="$dotfiles"

flake="$dotfiles/hosts/current/flake.nix"
flakeDir="$(dirname "$flake")"
mkdir -p "$flakeDir"

# https://discourse.nixos.org/t/local-personal-development-tools-with-flakes/22714/8
cat <<EOF > "$flake"
{
  description = "Current host";
  inputs.parent.url = "path:../..";
  outputs = { self, parent }:
    let
      args = {
        hostConfig = ../$hostId.nix;
        username = "$USER";
        homeDirectory = "$HOME";
        machine = {
          dotfilesDirectory = "$dotfiles";
          macOSversion = "$(sw_vers -productVersion)";
        };
      };
    in {
      packages."x86_64-darwin".default = parent.legacyPackages."x86_64-darwin".dotfiles args;
      packages."aarch64-darwin".default = parent.legacyPackages."aarch64-darwin".dotfiles args;
    };
}
EOF

git -C "$dotfiles" add --intent-to-add "$flake"
git -C "$dotfiles" update-index --assume-unchanged "$flake"

systemEnv="$(
  nix build \
    --no-link \
    --show-trace \
    --print-out-paths \
    --no-write-lock-file \
    "$dotfiles/hosts/current"
)"

echo "$systemEnv"

VERBOSE=1 "$systemEnv/activate"

previousGeneration="$(currentGeneration)"

echo "Installing packages to Nix profile"
# We need to resolve the symlink to the buildEnv here, otherwise
# Nix will use the $systemEnv buildEnv as the source of the profile
# (meaning we get ~/.nix-profile/env and ~/.nix-profile/activate)
nix-env --set "$(/usr/bin/readlink "$systemEnv/env")" --show-trace

newGeneration="$(currentGeneration)"

if [ "$previousGeneration" = "$newGeneration" ]; then
  echo "==> No change, reusing generation $previousGeneration"
else
  echo "==> Now using profile generation $newGeneration"
fi

rm -rf "$flakeDir"
