#!/bin/sh

# Usage:
# `./run_with_log <script name>
# e.g. `./run_with_log bootstrap.sh

current_timestamp=$(date -u +%FT%TZ | tr ":" "-")
log_filename=$(basename "$1" | sed -e 's/^\.//g' -e 's/[\.\/]/-/g')

sh "$1" 2>&1 | tee "$HOME/Desktop/$log_filename-$current_timestamp.log"

